### ISSUE TITLE
Why update a readme?

### ISSUE THREAD

**Issue by Erhushenshou** [slvrfn/vectorized_convolution#1]
Did you receive any comments from the omscs 7643? I am just curious about it. Thanks.

**Comment by slvrfn** [comment]
I don't understand your question here, can you elaborate?

**Comment by Erhushenshou** [comment]
> I don't understand your question here, can you elaborate?

I wonder why you update your repo on Feb 19th after 3 years. Seemed like this is part from CS 7643 assignment 2. Did you get any warnings from TAs to update and revise code? I learned a lot from your implementatiin in terms of the backward process.

**Comment by slvrfn** [comment]
no, i've had no communication with the TA's. I made a point when i created the repo to have it "loose" enough so that they would hopefully never have a problem with me sharing the repo here 

I havent updated any code, just the url pointing to my personal blog describing the repo. Im doing some re-structuring of my personal site(s) so there will likely be another url update soon

**Comment by slvrfn** [comment]
I'm glad my work was able to help at least one person! Makes it all worth it

**Comment by Erhushenshou** [comment]
Your update on the same submission date made me feel nervous about being caught viloated to the honor code. But I only borrowed your dilation methods to correct error in my code.

**Comment by slvrfn** [comment]
i have no say in the matter, but from my experience you should be fine

**Comment by Erhushenshou** [comment]
When did you take the course then? It really took me days to figure it out using as_strided.
